---
title: "ECS 132 - Homework #6"
author:  Bishal Thapa,  \break bthapa@ucdavis.edu # Include your name, and UC Davis email
date: "r Sys.Date()"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\pagebreak[4]

# Problem 1
Cars cross a certain point in the highway in accordance with a Poisson process with rate $\lambda$ = 3 cars per minute.  
1. If I run blindly across the highway it takes me s = 10 seconds to cross the road. Assume that if I am on the highway when a car passes by, then I will be injured. What is the probability that I will be uninjured?     
2. Suppose that I am agile enough to escape from a single car, but if I encounter 2 or more cars while attempting to cross the highways, I will be injured. However, it now takes me s = 30 seconds to cross the highway. What is the probability that I will be uninjured while crossing the highway?  

## 1.1
$$
  \begin{aligned}
    P(Uninjured) &= P(N(s) = 0) = e^{-\lambda*s} \\
                 &=  e^{-4*\frac{10}{60}} \\
                 &= 0.5134
  \end{aligned}
$$
  
## 1.2
$$
  \begin{aligned}
    P(Uninjured) &= P(N(s) = 0 || N(s) = 1) \\
                 &= e^{-\lambda*s} + \lambda*s*e^{-\lambda*s} \\
                 &= e^{-4*\frac{30}{60}} + 4*\frac{30}{60}*e^{-4*\frac{30}{60}} \\
                 &= 0.406
  \end{aligned}
$$
  
# Problem 2
Consider a memory system which only allows you to do sequential search. For example a read/write tape drive. If you want to look for a file you have to search sequentially looking at the first file, then the second file and so on until you find the file. A reasonable strategy would be place the most recently retrieved file at the front (imagine that the tape system can magically do this). This way the files that are accessed more often will be "at the front" and require less searching time in the long run. Consider the case with only 3 files A, B, and C.  
1. Let $X_n$ denote the sequence of the memory system after the nth search. For example, if the files were ordered A and then B followed by C, then $X_0 = ABC$. Enumerate the state space.  
2. If $X_0 = ABC$, list all possible states of X1.  
3. If $p_A, p_B$, and $p_C = 1 ??? p_A ??? p_B$ are the probabilities with which files A, B, and C are accessed, respectively, determine the one-step state transition matrix.  
4. If $pA = 0.6$, $pB = 0.10$, $pC = 0.3$, determine the steady state probability for the file order ABC.  
5. In general show that the steady state probability of the state ABC is given by
  
## 2.1
$$
  \begin{aligned}
    SS &= \{ A, B, C \}
  \end{aligned}
$$
  
## 2.2
$$
  \begin{aligned}
    X_0 &= ABC \\
    X_1 &= \{ ABC, BAC, CBA \}
  \end{aligned}
$$ 
  
## 2.3
$$
  \begin{aligned}
  P =
    \begin{bmatrix}
      p_A & p_B & p_C & 0 & 0 & 0 \\
      p_A & p_B & 0 & p_C & 0 & 0 \\
      p_A & 0 & p_C & 0 & p_B & 0 \\
      0 & p_B & 0 & p_C & 0 & p_A \\
      0 & 0 & p_C & 0 & p_B & p_A \\
      0 & 0 & 0 & p_C & p_B & p_A \\
    \end{bmatrix}
  \end{aligned}
$$ 
  
## 2.4
$$
  \begin{aligned}
  P &=
    \begin{bmatrix}
      p_A & p_B & p_C & 0 & 0 & 0 \\
      p_A & p_B & 0 & p_C & 0 & 0 \\
      p_A & 0 & p_C & 0 & p_B & 0 \\
      0 & p_B & 0 & p_C & 0 & p_A \\
      0 & 0 & p_C & 0 & p_B & p_A \\
      0 & 0 & 0 & p_C & p_B & p_A \\
    \end{bmatrix} \\
    
    P_{ABC} &=
    \begin{bmatrix}
      0.6 & 0.1 & 0.3 & 0 & 0 & 0 \\
      0.6 & 0.1 & 0 & 0.3 & 0 & 0 \\
      0.6 & 0 & 0.3 & 0 & 0.1 & 0 \\
      0 & 0.1 & 0 & 0.3 & 0 & 0.6 \\
      0 & 0 & 0.3 & 0 & 0.1 & 0.6 \\
      0 & 0 & 0 & 0.3 & 0.1 & 0.6 \\
    \end{bmatrix} 
    *
    \begin{bmatrix}
      0.6 \\
      0.6 \\
      0.6 \\
      0 \\
      0 \\
      0 \\
    \end{bmatrix} \\
    &= \begin{bmatrix} 0.6 & 0.42 & 0.54 & 0.06 & 0.18 & 0 \end{bmatrix}
  \end{aligned}
$$ 

solve(A *{ {0.6, 0.1,0.3,0,0,0}, {0.6,0.1,0,0.3,0 ,0}, {0.6,0,0.3,0,0.1,0}, {0,0.1,0,0.3,0,0.6}, {0,0,0.3,0,0.1,0.6}, {0,0,0,0.3,0.1,0.6} } = A,A)


# Classmate Collaborators

Inclulde the names and email IDs of everyone you collaborated with. You are free to discuss with your peers but everyone's work must be individual.
